Trooze-master/Trooze/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('music.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Trooze-master/home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^', views.gotomusic, name='gotomusic'),
]

Trooze-master/music/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'music'

urlpatterns = [
    # albums view
    url(r'^', views.landing_page, name="landing_page"),

    # register user
    url(r'^register/$', views.UserRegisterView.as_view(), name="register"),

    # register artist
    url(r'^register-artist/$', views.UserRegisterArtistView.as_view(), name="register_artist"),

    # login user
    url(r'^login/$', views.UserLoginView.as_view(), name="login"),

    # logout user
    url(r'^logout/$', views.logout_user, name="logout"),

    url(r'^artists/', include([
        # search artists
        url(r'^search/form/$', views.search_artists_form, name="search_artists_form"),
        url(r'^search/$', views.search_artists, name="search_artists"),
    ])),

    url(r'^artist/(?P<artist_id>[0-9]+)/', include([
        # artist details
        url(r'^$', views.artist_details, name="artist_details"),
        # update artist details
        url(r'^update/$', views.ArtistUpdateView.as_view(), name="artist_update"),
        # follow artist
        url(r'^follow/$', views.follow_artist, name="follow_artist"),
        # unfollow artist
        url(r'^unfollow/$', views.unfollow_artist, name="unfollow_artist"),
        # like artist
        url(r'^like/$', views.like_artist, name="like_artist"),
        # unlike artist
        url(r'^unlike/$', views.unlike_artist, name="unlike_artist"),
        # upload photo
        url(r'^upload-photo/$', views.artist_photo_upload, name="artist_photo_upload"),
        # artist events
        url(r'^event/', include([
            # create event
            url(r'^create/$', views.ArtistCreateEventView.as_view(), name="create_event"),
            # specific event
            url(r'^(?P<event_id>[0-9]+)/', include([
                # event details
                url(r'^$', views.event_details, name="event_details"),
                # delete event
                url(r'^delete/$', views.delete_event, name="delete_event"),
                # update event
                url(r'^update/$', views.EventUpdateView.as_view(), name="update_event"),
                # like event
                url(r'^like/$', views.like_event, name="like_event"),
                # unlike event
                url(r'^unlike/$', views.unlike_event, name="unlike_event"),
                # subscribe event
                url(r'^subscribe/$', views.subscribe_event, name="subscribe_event"),
                # unsubscribe event
                url(r'^unsubscribe/$', views.unsubscribe_event, name="unsubscribe_event"),
                # join event
                url(r'^join/$', views.join_event, name="join_event"),
                # quit event
                url(r'^quit/$', views.quit_event, name="quit_event"),
                # upload photo
                url(r'^upload-photo/$', views.event_photo_upload, name="event_photo_upload"),
            ])),
        ])),
    ])),

    url(r'^album/', include([
        # search album
        url(r'^search/$', views.album_search, name="album_search"),
        # create album
        url(r'^create/$', views.AlbumCreateView.as_view(), name="album_create"),
    ])),

    url(r'^album/(?P<album_id>[0-9]+)/', include([
        # single album view
        url(r'^$', views.album_details, name="album_details"),
        # update album
        url(r'^update/$', views.AlbumUpdateView.as_view(), name="album_update"),
        # delete album
        url(r'^delete/$', views.delete_album, name="album_delete"),
        # like album
        url(r'^like/$', views.like_album, name="like_album"),
        # unlike album
        url(r'^unlike/$', views.unlike_album, name="unlike_album"),
        # copy album
        url(r'^copy/$', views.copy_album, name="copy_album"),
        # upload photo
        url(r'^upload-photo/$', views.album_photo_upload, name="album_photo_upload"),
    ])),

    url(r'^albums/', include([
        # albums view
        url(r'^$', views.AlbumsView.as_view(), name="albums"),
        # search for albums
        url(r'^search/form/$', views.search_albums_form, name="search_albums_form"),
        url(r'^search/$', views.search_albums, name="search_albums"),
        # all songs
        url(r'^songs/$', views.all_songs, name="all_songs"),
    ])),


    url(r'^album/(?P<album_id>[0-9]+)/song/', include([
        # create song
        url(r'^create/$', views.SongCreateView.as_view(), name="song_create"),
        # specific song
        url(r'^(?P<song_id>[0-9]+)/', include([
            # update song
            url(r'^update/$', views.SongUpdateView.as_view(), name="song_update"),
            # delete song
            url(r'^delete/$', views.delete_song, name="song_delete"),
            # favorite song
            url(r'^favorite/$', views.favorite_song, name="favorite_song"),
            # upload audio
            url(r'^upload-song/$', views.upload_song, name="upload_song"),
        ])),
    ])),
]

Trooze-master/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^', include('home.urls')),
]

Trooze-master/music/views.py
from django.views.generic import (
    View,
    ListView,
)
from django.db.models import (
    Q,
    CharField,
    Value as V,
)
from django.db.models.functions import (
    Length,
    Concat,
)
from django.contrib.auth import (
    authenticate,
    login,
    logout
)
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.forms import modelform_factory
from django.core.paginator import (
    Paginator,
    PageNotAnInteger,
    EmptyPage
)
from django.conf import settings
from .models import (
    Album,
    Song,
    Artist,
    Event,
)
from .forms import (
    UserRegisterForm,
    ArtistForm,
    UserLoginForm,
    AlbumForm,
    SongForm,
    ArtistSongForm,
    EventForm,
)
from .const import (
    IMAGE_FILE_TYPES,
    AUDIO_FILE_TYPES,
)
from .utils import (
    bad_image_file_type,
    bad_audio_file_type,
    song_already_exists,
    album_already_exists,
    create_copied_album,
    create_copied_song
)

"""""""""""""""""""""
    Landing Page
"""""""""""""""""""""


def landing_page(request):
    if request.user.is_authenticated:
        if hasattr(request.user, 'artist'):
            return redirect('music:artist_details', artist_id=request.user.artist.id)
        return redirect('music:albums')
    return render(request, 'music/home/home.html')


"""""""""""""""""""""""
   User Registration
"""""""""""""""""""""""


class UserRegisterView(View):
    form_class = UserRegisterForm
    template_name = 'music/home/registration/register.html'

    def get(self, request):
        context = {'form': self.form_class(), 'not_logged_in': True}
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST or None)
        context = {'form': form, 'not_logged_in': True}
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('music:albums')
            return render(request, self.template_name, context)
        return render(request, self.template_name, context)


class UserRegisterArtistView(View):
    form_class = UserRegisterForm
    form_class2 = ArtistForm
    template_name = 'music/home/registration/register_artist.html'

    def get(self, request):
        context = {'form': self.form_class(), 'form2': self.form_class2(), 'not_logged_in': True}
        return render(request, self.template_name, context)

    def post(self, request):
        user_form = self.form_class(request.POST or None)
        artist_form = self.form_class2(request.POST or None, request.FILES or None)
        context = {'form': user_form, 'form2': artist_form, 'not_logged_in': True}
        if user_form.is_valid() and artist_form.is_valid():
            user = user_form.save(commit=False)
            user.artist = artist_form.save(commit=False)
            # check uploaded file type
            username = user_form.cleaned_data['username']
            password = user_form.cleaned_data['password1']
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('music:artist_details', artist_id=user.artist.id)
            return render(request, self.template_name, context)
        return render(request, self.template_name, context)


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'music/home/registration/login.html'

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class(), 'not_logged_in': True})

    def post(self, request):
        form = self.form_class()
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                if hasattr(user, 'artist'):
                    return redirect('music:artist_details', artist_id=user.artist.id)
                return redirect('music:albums')
            else:
                return render(request, 'error.html', {'message': 'This account has been disabled'})
        context = {'form': form, 'not_logged_in': True}
        return render(request, self.template_name, context)


def logout_user(request):
    logout(request)
    return redirect('music:login')


"""""""""""""""""
   Album Views
"""""""""""""""""


# albums view
class AlbumsView(LoginRequiredMixin, ListView):
    template_name = 'music/albums.html'
    context_object_name = 'albums'

    def get_queryset(self):
        return Album.get_albums_by_user(self.request.user)


# single album view
@login_required
def album_details(request, album_id):
    album = Album.cached_album_by_pk(album_id, related='user')
    songs = album.song_set.all()
    context = {'songs': songs, 'album': album}
    return render(request, 'music/album_details.html', context)


"""""""""""""""""
  Album Creation
"""""""""""""""""


class AlbumCreateView(LoginRequiredMixin, View):
    form_class = AlbumForm
    template_name = 'music/album_form.html'

    def get(self, request):
        form = self.form_class()
        # if artist, pre put name
        if hasattr(request.user, 'artist'):
            artist_name = request.user.artist.full_name
            form = self.form_class({'artist': artist_name})
        context = {'form': form, 'action': 'create'}
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST or None, request.FILES or None)
        if form.is_valid():
            album = form.save(commit=False)
            album.user = request.user
            # check if album already exists
            if Album.get_albums_by_user(request.user).filter(name__exact=album.name).exists():
                return album_already_exists(request, form, album)
            if request.FILES:  # make sure FILES dictionary is not empty
                file_type = album.logo_file.url.split('.')[-1].lower()
                if file_type not in IMAGE_FILE_TYPES:
                    return bad_image_file_type(request, form, album)
            album.save()
            return redirect('music:albums')
        context = {'form': form, 'action': 'create'}
        return render(request, self.template_name, context)


"""""""""""""""""
  Album Update
"""""""""""""""""


class AlbumUpdateView(LoginRequiredMixin, View):
    form_class = modelform_factory(Album, form=AlbumForm, exclude=['logo_file'])
    template_name = 'music/album_form.html'

    def get(self, request, album_id):
        album = Album.cached_album_by_pk(album_id, related='user')
        if album.user != request.user:
            return render(request, 'error.html', {'message': 'You can not edit this album'})
        form = self.form_class(album.as_object())
        context = {'form': form, 'album': album, 'action': 'update'}
        return render(request, self.template_name, context)

    def post(self, request, album_id):
        album = Album.cached_album_by_pk(album_id, related='user')
        if album.user != request.user:
            message = 'You are trying to make an action you are not authorized to do'
            return render(request, 'error.html', {'message': message})
        form = self.form_class(request.POST or None, request.FILES or None)
        if form.is_valid():
            updated_album = form.save(commit=False)
            all_albums_except_current = Album.get_albums_by_user(request.user).exclude(pk=album_id)
            # check if album already exists
            if all_albums_except_current.filter(name__exact=updated_album.name).exists():
                return album_already_exists(request, form, album, action='update')
            album.update_fields(updated_album, exclude=['logo_file', 'user'])
            album.save()
            return redirect('music:album_details', album_id=album_id)
        context = {'form': form, 'album': album, 'action': 'update'}
        return render(request, self.template_name, context)


"""""""""""""""""
  Album Deletion
"""""""""""""""""


# album delete
@login_required
def delete_album(request, album_id):
    album = Album.cached_album_by_pk(album_id, related='user')
    if album.user == request.user:
        album.delete()
        return redirect('music:albums')
    message = 'You can not delete this album'
    return render(request, 'error.html', {'message': message})


"""""""""""""""""""""
  Album Photo Upload
"""""""""""""""""""""


@login_required
@csrf_exempt
def album_photo_upload(request, album_id):
    album = Album.cached_album_by_pk(album_id, related='user')
    if request.user != album.user:
        return render(request, 'error.html', {'message': 'You can not upload a picture for this album'})
    file = request.FILES.get('file')
    if file is None:
        return JsonResponse({'no_file': False})
    file_type = file.name.split('.')[-1].lower()
    if file_type not in IMAGE_FILE_TYPES:
        return JsonResponse({'not_image': True})
    album.file_to_delete = album.logo_file
    album.logo_file = file
    album.save()
    return JsonResponse({'uploaded': True})


"""""""""""""""""
  Album Search
"""""""""""""""""


@login_required
def album_search(request):
    query = request.GET.get('q', None)
    albums = []
    if query:
        albums = Album.get_albums_by_user(request.user)
        albums = albums.filter(
            Q(name__icontains=query) |

Trooze-master/music/templates/music/partials/albums/albums_list.html
{% if albums or events %}
    <div class="col-md-3 col-sm-4">

        {% if albums %}
        <ul class="list-group">
            <li class="list-group-item">
                <span class="float-left">Albums List:</span>
                <span class="float-right">({{ albums|length }})</span>
                <div class="clear"></div>
            </li>
          {% for album in albums %}
            <li class="list-group-item">
                <!-- album details -->
                <a href="{% url 'music:album_details' album.id %}" class="float-left">
                    <strong>{{ album.name }}</strong>&nbsp;&nbsp;<small>({{ album.artist }})</small>
                </a>
                {% if request.user == album.user %}
                    <!-- delete confirm -->
                    <a href="{% url 'music:album_delete' album.id %}" class="float-right delete-album" data-name="{{ album.name }}" role="button">
                        <span class="glyphicon glyphicon-trash"></span>
                    </a>
                {% else %}
                    <a href="{% url 'music:copy_album' album.id %}" data-name="{{ album.name }}" class="btn btn-default btn-sm float-right copy-album" role="button">
                        <span class="glyphicon glyphicon-save"></span>
                    </a>
                {% endif %}
                <div class="clear"></div>
            </li>
          {% endfor %}
        </ul>
        {% endif %}

        <!-- if artist's events are supplied, include them -->
        {% include 'music/partials/albums/events_list.html' %}
    </div>
{% endif %}

Trooze-master/music/templates/music/partials/albums/albums_view.html
{% load staticfiles %}
<div class="col-md-9 col-sm-8">
{% if albums %}
    <div class="row albums">
        {% for album in albums %}
          <div class="col-sm-9 col-md-5 album">
              {% include 'music/partials/single_album.html' %}
          </div>
        {% endfor %}
    </div>
{% else %}
    {% if query %}
        <div class="alert alert-danger" role="alert">
            <p class="large">The query "{{ query }}" returned no matching albums.</p><br>
            <a href="{% url 'music:albums' %}" class="alert-link">
                <span class="glyphicon glyphicon-arrow-left"></span>
                Back to your albums list
            </a>
        </div>
    {% else %}
        <div>
            <h5 class="alert alert-danger">No albums.</h5>
        </div>
    {% endif %}
{% endif %}
</div>

Trooze-master/music/templates/music/partials/albums/events_list.html
{% if events %}
<ul class="list-group">
    <li class="list-group-item">
        <span class="float-left">Events List:</span>
        <span class="float-right">({{ events|length }})</span>
        <div class="clear"></div>
    </li>
  {% for event in events %}
    <li class="list-group-item">
        <!-- album details -->
        <a href="{% url 'music:event_details' event.artist.id event.id %}" class="float-left">
            {% if event.place_image %}
                <img src="{{ event.place_image.url }}" alt="{{ event.title }}" title="{{ event.title }}" width="20" />
            {% endif %}
            <strong>{{ event.title }}</strong>
        </a>
        {% if request.user.artist and request.user.artist == event.artist %}
            <!-- delete confirm -->
            <a href="{% url 'music:delete_event' event.artist.id event.id %}"
               class="float-right delete-event" data-name="{{ event.title }}" role="button">
                <span class="glyphicon glyphicon-trash"></span>
            </a>
        {% else %}
            <a href="" data-name="{{ event.title }}" class="btn btn-default btn-sm float-right copy-album" role="button">
                <span class="glyphicon glyphicon-eye-open"></span>
            </a>
        {% endif %}
        <div class="clear"></div>
    </li>
  {% endfor %}
</ul>
{% endif %}