Trooze-master/Trooze/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('music.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Trooze-master/home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^', views.gotomusic, name='gotomusic'),
]

Trooze-master/music/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'music'

urlpatterns = [
    # albums view
    url(r'^', views.landing_page, name="landing_page"),

    # register user
    url(r'^register/$', views.UserRegisterView.as_view(), name="register"),

    # register artist
    url(r'^register-artist/$', views.UserRegisterArtistView.as_view(), name="register_artist"),

    # login user
    url(r'^login/$', views.UserLoginView.as_view(), name="login"),

    # logout user
    url(r'^logout/$', views.logout_user, name="logout"),

    url(r'^artists/', include([
        # search artists
        url(r'^search/form/$', views.search_artists_form, name="search_artists_form"),
        url(r'^search/$', views.search_artists, name="search_artists"),
    ])),

    url(r'^artist/(?P<artist_id>[0-9]+)/', include([
        # artist details
        url(r'^$', views.artist_details, name="artist_details"),
        # update artist details
        url(r'^update/$', views.ArtistUpdateView.as_view(), name="artist_update"),
        # follow artist
        url(r'^follow/$', views.follow_artist, name="follow_artist"),
        # unfollow artist
        url(r'^unfollow/$', views.unfollow_artist, name="unfollow_artist"),
        # like artist
        url(r'^like/$', views.like_artist, name="like_artist"),
        # unlike artist
        url(r'^unlike/$', views.unlike_artist, name="unlike_artist"),
        # upload photo
        url(r'^upload-photo/$', views.artist_photo_upload, name="artist_photo_upload"),
        # artist events
        url(r'^event/', include([
            # create event
            url(r'^create/$', views.ArtistCreateEventView.as_view(), name="create_event"),
            # specific event
            url(r'^(?P<event_id>[0-9]+)/', include([
                # event details
                url(r'^$', views.event_details, name="event_details"),
                # delete event
                url(r'^delete/$', views.delete_event, name="delete_event"),
                # update event
                url(r'^update/$', views.EventUpdateView.as_view(), name="update_event"),
                # like event
                url(r'^like/$', views.like_event, name="like_event"),
                # unlike event
                url(r'^unlike/$', views.unlike_event, name="unlike_event"),
                # subscribe event
                url(r'^subscribe/$', views.subscribe_event, name="subscribe_event"),
                # unsubscribe event
                url(r'^unsubscribe/$', views.unsubscribe_event, name="unsubscribe_event"),
                # join event
                url(r'^join/$', views.join_event, name="join_event"),
                # quit event
                url(r'^quit/$', views.quit_event, name="quit_event"),
                # upload photo
                url(r'^upload-photo/$', views.event_photo_upload, name="event_photo_upload"),
            ])),
        ])),
    ])),

    url(r'^album/', include([
        # search album
        url(r'^search/$', views.album_search, name="album_search"),
        # create album
        url(r'^create/$', views.AlbumCreateView.as_view(), name="album_create"),
    ])),

    url(r'^album/(?P<album_id>[0-9]+)/', include([
        # single album view
        url(r'^$', views.album_details, name="album_details"),
        # update album
        url(r'^update/$', views.AlbumUpdateView.as_view(), name="album_update"),
        # delete album
        url(r'^delete/$', views.delete_album, name="album_delete"),
        # like album
        url(r'^like/$', views.like_album, name="like_album"),
        # unlike album
        url(r'^unlike/$', views.unlike_album, name="unlike_album"),
        # copy album
        url(r'^copy/$', views.copy_album, name="copy_album"),
        # upload photo
        url(r'^upload-photo/$', views.album_photo_upload, name="album_photo_upload"),
    ])),

    url(r'^albums/', include([
        # albums view
        url(r'^$', views.AlbumsView.as_view(), name="albums"),
        # search for albums
        url(r'^search/form/$', views.search_albums_form, name="search_albums_form"),
        url(r'^search/$', views.search_albums, name="search_albums"),
        # all songs
        url(r'^songs/$', views.all_songs, name="all_songs"),
    ])),


    url(r'^album/(?P<album_id>[0-9]+)/song/', include([
        # create song
        url(r'^create/$', views.SongCreateView.as_view(), name="song_create"),
        # specific song
        url(r'^(?P<song_id>[0-9]+)/', include([
            # update song
            url(r'^update/$', views.SongUpdateView.as_view(), name="song_update"),
            # delete song
            url(r'^delete/$', views.delete_song, name="song_delete"),
            # favorite song
            url(r'^favorite/$', views.favorite_song, name="favorite_song"),
            # upload audio
            url(r'^upload-song/$', views.upload_song, name="upload_song"),
        ])),
    ])),
]

Trooze-master/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^', include('home.urls')),
]

Trooze-master/music/models.py
import os
from django.db import models
from django.contrib.auth.models import User
from django.forms.models import model_to_dict
from django.dispatch import receiver
from django.core.cache import cache
from django.db.models import Q
import music.model_funcs as fn
from .const import (
    MUSICAL_GENRES,
    COUNTRIES,
    AREAS,
    GENDER,
    MONEY,
)

"""""""""""
  Artist
"""""""""""


class Artist(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    stage_name = models.CharField(max_length=50, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER, default=GENDER[0][0])
    country = models.CharField(max_length=50, choices=COUNTRIES, default=COUNTRIES[0][0])
    area = models.CharField(max_length=10, choices=AREAS, default=AREAS[0][0])
    picture = models.FileField()
    likers = models.ManyToManyField(User, related_name='artist_field', blank=True)
    followers = models.ManyToManyField(User, related_name='artists', blank=True)
    about = models.TextField(blank=True)
    facebook = models.URLField(blank=True)
    instagram = models.URLField(blank=True)
    twitter = models.URLField(blank=True)
    created = models.DateTimeField(blank=True)
    updated = models.DateTimeField(blank=True)

    def save(self, *args, **kwargs):
        fn.save(self, *args, **kwargs)
        self.cache_artist()

    def as_object(self):  # turn django model into a plain object
        return fn.as_object(self)

    @property
    def full_name(self):
        return self.first_name + ' ' + self.last_name

    @property
    def location(self):
        return self.country + ', ' + self.area

    def update_fields(self, updater, fields=None, exclude=None):  # update model fields
        fn.update_fields(self, updater, fields, exclude)

    def is_followed_by(self, user):
        return self.followers.all().filter(id=user.id).exists()

    def is_liked_by(self, user):
        return self.likers.all().filter(id=user.id).exists()

    def cache_artist(self):
        cache.set(self.__cache_name__, self)

    @property
    def __cache_name__(self):
        return 'artists.{0}'.format(self.pk)

    @classmethod
    def cached_artist_by_pk(cls, pk, related=None):
        return fn.cached_object_by_pk(cls, pk, related=related)

    def __str__(self):
        return 'Artist username- {0}'.format(self.user.username)


# save artist when user saved
@receiver(models.signals.post_save, sender=User)
def save_artist_on_save_user(sender, instance, created, **kwargs):
    if created and hasattr(instance, 'artist'):
        artist = instance.artist
        artist.user = instance
        artist.save()


"""""""""""""""""""""
    Recommendation
"""""""""""""""""""""


class Recommendation(models.Model):
    on_user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    date = models.DateTimeField()
    rate = models.PositiveIntegerField(default=1)
    created = models.DateTimeField(blank=True)
    updated = models.DateTimeField(blank=True)

    def save(self, *args, **kwargs):
        fn.save(self, *args, **kwargs)

    class Meta:
        ordering = ('-date', '-rate',)


"""""""""
  Event
"""""""""


class Event(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    start_date = models.DateTimeField()
    end_date = models.DateTimeField()
    start_time = models.CharField(max_length=5)
    end_time = models.CharField(max_length=5)
    price = models.FloatField(default=0.0)
    currency = models.CharField(max_length=60, choices=MONEY, default=MONEY[0][0])
    location = models.CharField(max_length=90)
    country = models.CharField(max_length=70)
    city = models.CharField(max_length=70)
    street = models.CharField(max_length=80)
    street_number = models.CharField(max_length=6)
    place_image = models.FileField()
    description = models.TextField()
    people_limit = models.PositiveIntegerField(blank=True, null=True)
    participants = models.ManyToManyField(User, related_name='events')
    subscribers = models.ManyToManyField(User, related_name='events_list')
    likers = models.ManyToManyField(User, related_name='events_arr')
    created = models.DateTimeField(blank=True)
    updated = models.DateTimeField(blank=True)

    class Meta:
        ordering = ('start_date',)

    def save(self, *args, **kwargs):
        fn.save(self, *args, **kwargs)
        self.cache_event()

    def as_object(self):
        return fn.as_object(self)

    @property
    def is_free(self):
        return int(self.price) == 0

    @property
    def num_people(self):
        return self.participants.count()

    @property
    def num_subscribers(self):
        return self.subscribers.count()

    @property
    def likes(self):
        return self.likers.count()

    @property
    def get_location(self):
        return self.country + ', ' + self.city

    @property
    def get_address(self):
        return self.street + ' ' + self.street_number

    @property
    def get_currency(self):
        symbol = self.currency.split('(')[1].replace(')', '')
        if symbol:
            return symbol
        else:
            return self.currency.split('(')[0]

    @property
    def days_duration(self):
        return self.end_date - self.start_date

    @property
    def has_room_left(self):
        if not self.people_limit:
            return True
        return self.num_people < self.people_limit

    def update_fields(self, updater, fields=None, exclude=None):  # update model fields
        fn.update_fields(self, updater, fields, exclude)

    def is_user_joined(self, user):
        return self.participants.all().filter(id=user.id).exists()

    def is_user_subscribed(self, user):
        return self.subscribers.all().filter(id=user.id).exists()

    def is_liked_by(self, user):
        return self.likers.all().filter(id=user.id).exists()

    @property
    def __cache_name__(self):
        return 'events.{0}'.format(self.pk)

    def cache_event(self):
        cache.set(self.__cache_name__, self)

    @classmethod
    def cached_event_by_pk(cls, pk, related=None):
        return fn.cached_object_by_pk(cls, pk, related=related)


# make sure to remove event image file when model deleted
@receiver(models.signals.post_delete, sender=Event)
def auto_delete_event_image_on_delete(sender, instance, **kwargs):
    if instance.place_image:
        if os.path.isfile(instance.place_image.path):  # check if file exists
            os.remove(instance.place_image.path)  # remove from storage
        cache.delete(instance.__cache_name__)  # delete cache


"""""""""""""""
 Notification
"""""""""""""""


class Notification(models.Model):
    by = models.ForeignKey(User)
    message = models.TextField()
    date = models.DateTimeField()
    is_critical = models.BooleanField(default=False)

    class Meta:
        ordering = ('-is_critical', '-date',)


"""""""""
  Album
"""""""""


class Album(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    artist = models.CharField(max_length=35)
    name = models.CharField(max_length=60)
    genre = models.CharField(max_length=50, choices=MUSICAL_GENRES)
    logo = models.URLField(blank=True)
    logo_file = models.FileField(blank=True, null=True)
    likers = models.ManyToManyField(User, related_name="albums")
    created = models.DateTimeField(blank=True)
    updated = models.DateTimeField(blank=True)

    class Meta:
        ordering = ('name',)

    def save(self, *args, **kwargs):  # could also be done using pre_save signal
        fn.save(self, *args, **kwargs)
        self.cache_album()

    def as_object(self):  # turn django model into a plain object
        return fn.as_object(self)

    def update_fields(self, updater, fields=None, exclude=None):  # update model fields
        fn.update_fields(self, updater, fields, exclude)

    def get_copy(self):
        return model_to_dict(self, exclude=['id', 'created', 'updated', 'user', 'likers'])

    def is_liked_by(self, user):
        return self.likers.all().filter(id=user.id).exists()

    @property
    def has_downloadable_songs(self):
        return self.song_set.filter(
            Q(is_downloadable=True) &
            Q(is_playable=True)
        ).exists()

    @classmethod
    def get_albums_by_user(cls, user):
        return cls.objects.filter(user=user)

    def cache_album(self):
        cache.set(self.__cache_name__, self)

    @property
    def __cache_name__(self):
        return 'albums.{0}'.format(self.pk)

    @classmethod
    def cached_album_by_pk(cls, pk, related=None):
        return fn.cached_object_by_pk(cls, pk, related=related)

    def __str__(self):
        return 'Album: {0}, Artist: {1}'.format(self.name, self.artist)


# make sure to remove image file when model deleted
@receiver(models.signals.post_delete, sender=Album)
def auto_delete_image_on_delete(sender, instance, **kwargs):
    if instance.logo_file:
        if os.path.isfile(instance.logo_file.path):  # check if file exists
            os.remove(instance.logo_file.path)  # remove from storage
    cache.delete(instance.__cache_name__)  # delete from cache


"""""""""
  Song
"""""""""


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    audio_file = models.FileField()
    is_favorite = models.BooleanField(default=False)
    is_downloadable = models.BooleanField(default=True)
    is_playable = models.BooleanField(default=True)
    created = models.DateTimeField(blank=True)
    updated = models.DateTimeField(blank=True)

    class Meta:
        ordering = ('-is_favorite',)

    def save(self, *args, **kwargs):  # could also be done using pre_save signal
        fn.save(self, *args, **kwargs)
        self.cache_song()

Trooze-master/music/templates/music/album_details.html
{% extends 'music/base.html' %}

{% load staticfiles %}

{% block title %}Details- {{ album.name }}{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'music/css/songs.css' %}" />
<link rel="stylesheet" href="{% static 'music/css/snippets/song_player.css' %}" />
{% endblock %}

{% block script %}
<script src="{% static 'music/js/play_song.js' %}" async></script>
<script src="{% static 'music/js/search_song.js' %}" async></script>
    {% if request.user != album.user %}
        <script src="{% static 'music/js/like_unlike_album.js' %}" async></script>
        <script src="{% static 'music/js/copy_album.js' %}" async></script>
        {% if album.has_downloadable_songs %}
            <script src="{% static 'music/js/download_album.js' %}" async></script>
        {% endif %}
    {% else %}
        <script src="{% static 'music/js/favorite_song.js' %}" async></script>
        <script src="{% static 'music/js/delete_popup.js' %}" async></script>
        <script src="{% static 'music/js/snippets/components/photo_upload.js' %}"></script>
        <script>
            $('.change-photo').uploadPhoto("{% url 'music:album_photo_upload' album.id %}");
        </script>
        {% include 'music/snippets/upload_song_scripts.html' %}
    {% endif %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-md-5 col-sm-5">
        {% include 'music/partials/single_album.html' %}
    </div>
    <div class="col-md-7 col-sm-7">
        <div class="table-responsive songs-table-wrapper">
            {% if request.user == album.user %}
                <a href="{% url 'music:song_create' album.id %}" class="btn btn-success add-song" role="button">
                    <span class="glyphicon glyphicon-plus"></span> Add Song
                </a>
            {% endif %}
            {% if songs %}
                {% if request.user == album.user %}
                    <input type="text" id="search-song" class="form-control search-song float-right" placeholder="Search.." value="" />
                {% else %}
                    <input type="text" id="search-song" class="form-control search-song float-left" placeholder="Search.." value="" />
                    {% if album.has_downloadable_songs %}
                        <a href="{% url 'music:copy_album' album.id %}"
                           class="btn btn-success add-song float-right"
                           id="download-album" role="button"
                        >
                            Download <span class="glyphicon glyphicon-download" style="font-size:11px;"></span>
                        </a>
                    {% endif %}
                {% endif %}
                <div class="clear"></div>
                {% include 'music/songs.html' %}
            {% else %}
                <p class="alert alert-danger">No songs yet.</p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

Trooze-master/music/templates/music/album_form.html
{% extends 'music/base.html' %}

{% load staticfiles %}

{% block title %}Trooze- Album{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'music/css/form.css' %}" />
<link rel="stylesheet" href="{% static 'music/css/snippets/better_select_box.css' %}" />
{% endblock %}

{% block content %}
<h3 class="create-new-album">
    {% if action == 'create' %}
        Create An
    {% else %}
        Update "<strong>{{ album.name }}</strong>"
    {% endif %}
        Album:
</h3>
<div class="new-album">
    {% if action == 'create' %}
        <form action="{% url 'music:album_create' %}" method="post" enctype="multipart/form-data">
    {% else %}
        <form action="{% url 'music:album_update' album.id %}" method="post" enctype="multipart/form-data">
    {% endif %}
            {% include 'music/partials/form_template.html' %}
            <div class="form-group">
                <button type="submit" class="btn btn-success">
                    {% if action == 'create' %} Create {% else %} Update {% endif %}
                </button>
            </div>
        </form>
        {% if error_message %}
            <h5 class="alert-danger error-message">{{ error_message|safe }}</h5>
        {% endif %}
</div>
{% include 'music/snippets/const/genres.html' %}
{% endblock %}

{% block script %}
<script src="{% static 'music/js/snippets/components/better_select_box.js' %}"></script>
<script>
$(function() {
    $('select#id_genre').betterselect(GENRES, {
        selectPlaceholder: '--- Choose Genre ---',
        filterPlaceholder: 'Search Genre'
    });
});
</script>
{% endblock %}

Trooze-master/music/templates/music/albums.html
{% extends 'music/base.html' %}

{% load staticfiles %}

{% block title %}Trooze- Albums{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'music/css/albums.css' %}" />
{% endblock %}

{% block content %}
    <div class="add-album-button-container">
        {% if not albums or albums.0.user == request.user %}
            <a href="{% url 'music:album_create' %}" class="btn btn-success" role="button">
                <span class="glyphicon glyphicon-plus"></span> Add Album
            </a>
        {% endif %}
        <a href="{% url 'music:search_albums_form' %}" class="btn btn-danger" role="button">
            <span class="glyphicon glyphicon-search"></span> Search for Albums
        </a>
        <!-- pagination -->
        {% if albums and albums.0.user != request.user %}
            {% if albums.has_previous %}
                <a href="{% url 'music:search_albums' %}?genre={{ genre }}&artist={{ artist }}&album={{ name }}&page={{ albums.previous_page_number }}"
                   class="btn load-albums" role="button">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                    Prev
                </a>
            {% endif %}
            {% if albums.has_next %}
                <a href="{% url 'music:search_albums' %}?genre={{ genre }}&artist={{ artist }}&album={{ name }}&page={{ albums.next_page_number }}"
                   class="btn load-albums" role="button">
                    Next
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            {% endif %}
        {% endif %}
    </div>

    <div class="row">
        {% include 'music/partials/albums/albums_view.html' %}
        {% include 'music/partials/albums/albums_list.html' %}
    </div>
{% endblock %}

{% block script %}
    {% if albums %}
        {% if request.user != albums.0.user %}
            <script src="{% static 'music/js/like_unlike_album.js' %}"></script>
            <script src="{% static 'music/js/copy_album.js' %}"></script>
        {% else %}
            <script src="{% static 'music/js/delete_popup.js' %}"></script>
        {% endif %}
    {% endif %}
{% endblock %}

Trooze-master/music/templates/music/event_details.html
{% extends 'music/base.html' %}

{% load staticfiles %}

{% block head %}
    <link href="{% static 'music/css/artist.css' %}" rel="stylesheet" />
    <link href="{% static 'music/css/albums.css' %}" rel="stylesheet" />
<style>
#map {
    margin-bottom: 15px;
}
#map .gm-style-cc {
    display: none;
}
</style>
{% endblock %}

{% block content %}
<div class="row">
  <div class="col-lg-4 col-md-6 col-sm-6">
    <div class="panel">
      <div class="panel-heading event-heading">
        <h3 class="panel-title add">
            <i class="fa fa-code" aria-hidden="true"></i> {{ event.title }}
        </h3>
      </div>
      <div class="panel-body">
          <p>
              <span class="glyphicon glyphicon-pencil"></span> <strong>Event Description</strong>
          </p>
          <div class="add">{{ event.description }}</div>
          <div id="map"></div>
      </div>
      <div class="panel-footer event-footer">
            <span class="event-artist-name">
                <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                {{ event.artist.full_name }}
            </span>
            <span class="event-location">
                <i class="fa fa-globe"></i>
                {{ event.get_location }}
            </span>
            <span class="event-address">
                <i class="fa fa-map-marker"></i>
                {{ event.get_address }}
            </span>
            <span class="event-price float-right">
                {% if event.is_free %}
                    <i class="fa fa-angle-double-right" style="font-weight:800;" aria-hidden="true"></i>
                    <strong>Free</strong> entrance
                {% else %}
                    <i class="fa fa-credit-card-alt"></i>
                    {{ event.price }} {{ event.get_currency }}
                {% endif %}
            </span>
            <div class="clear"></div>
      </div>
    </div>
  </div>
  <div class="col-lg-5 col-lg-offset-3 col-md-offset-1 col-md-5 col-sm-6">
    <div class="thumbnail">
      <div class="image-wrapper">
          {% if event.place_image %}
            <img src="{{ event.place_image.url }}" alt="{{ event.title }}" title="{{ event.title }}">
          {% else %}
            <img src="{% static 'music/img/no_image.png' %}" alt="{{ event.title }}" title="{{ event.title }}" />
          {% endif %}
          {% if request.user.artist and request.user.artist == event.artist %}
            {% include 'music/partials/upload_new_photo.html' %}
          {% endif %}
      </div>
      <div class="caption">
        <div class="event-information">
            <p class="event-artist-name">
                <i class="fa fa-user-circle-o" aria-hidden="true"></i>
                <strong>Created by:</strong> {{ event.artist.full_name }}
            </p>
            <p class="event-location">
                <i class="fa fa-globe"></i>
                <strong>Location:</strong> {{ event.get_location }}
            </p>
            <p class="event-address">
                <i class="fa fa-map-marker"></i>
                <strong>Address:</strong> {{ event.get_address }}
            </p>
            <p class="event-price">
                {% if event.is_free %}
                    <i class="fa fa-angle-double-right" style="font-weight:800;" aria-hidden="true"></i>
                    <strong>Free</strong> entrance
                {% else %}
                    <i class="fa fa-money" aria-hidden="true"></i>
                    <strong>Price:</strong> {{ event.price }} {{ event.get_currency }}
                {% endif %}
            </p>
        </div>
        <div class="event-labels">
            <p>
                <i class="fa fa-calendar-check-o"></i>
                <span class="label label-custom joined-label">
                    {{ event.num_people }} participant{{ event.num_people|pluralize }}
                </span>
            </p>
            <p>
                <i class="fa fa-users"></i>
                <span class="label label-custom subscribed-label">
                    {{ event.num_subscribers }} subscriber{{ event.num_subscribers|pluralize }}
                </span>
            </p>
            <p>
                <span class="glyphicon glyphicon-thumbs-up"></span>
                <span class="label label-custom liked-label">
                    {{ event.likes }} like{{ event.likes|pluralize }}
                </span>
            </p>
        </div>
          <!-- TODO put in another section -->
        <div class="actions">
          {% if request.user.artist and request.user.artist == event.artist %}
              <div class="float-right">
                <a href="{% url 'music:update_event' event.artist.id event.id %}" class="btn btn-default btn-sm" role="button">
                    <span class="glyphicon glyphicon-edit"></span>
                </a>
                <a href="{% url 'music:delete_event' event.artist.id event.id %}"
                   class="delete-event btn btn-default btn-sm" data-name="{{ event.title }}" role="button">
                    <span class="glyphicon glyphicon-trash"></span>
                </a>
              </div>
              <div class="clear"></div>
        {% else %}
              <div class="float-left">
                  {% if request.user not in event.subscribers.all %}
                    {% if event.has_room_left %}
                        <a href="{% url 'music:subscribe_event' event.artist.id event.id %}"
                           class="btn btn-primary btn-sm sub-unsub-event" role="button">
                            <i class="fa fa-rss" aria-hidden="true"></i> Subscribe
                        </a>
                    {% endif %}
                  {% else %}
                    <a href="{% url 'music:unsubscribe_event' event.artist.id event.id %}"
                       class="btn btn-primary btn-sm sub-unsub-event" role="button">
                        <i class="fa fa-reply" aria-hidden="true"></i> Unsubscribe
                    </a>
                  {% endif %}
                  {% if request.user not in event.participants.all %}
                    {% if event.has_room_left %}
                        <a href="{% url 'music:join_event' event.artist.id event.id %}"
                           class="btn btn-success btn-sm join-quit-event" role="button">
                            <i class="fa fa-calendar-check-o" aria-hidden="true"></i> Join
                        </a>
                    {% endif %}
                  {% else %}
                        <a href="{% url 'music:quit_event' event.artist.id event.id %}"
                           class="btn btn-danger btn-sm join-quit-event" role="button">
                            <i class="fa fa-calendar-times-o" aria-hidden="true"></i> Quit
                        </a>
                  {% endif %}
              </div>
                {% if request.user not in event.likers.all %}
                  <a href="{% url 'music:like_event' event.artist.id event.id %}"
                     class="btn btn-warning btn-sm like-unlike-event float-right">
                    <span class="glyphicon glyphicon-thumbs-up"></span> Like
                  </a>
                {% else %}
                  <a href="{% url 'music:unlike_event' event.artist.id event.id %}"
                     class="btn btn-warning btn-sm like-unlike-event float-right">
                    <span class="glyphicon glyphicon-thumbs-down"></span> Unlike
                  </a>
                {% endif %}
              <div class="clear"></div>
        {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
{% if event %}
    {% if request.user.artist and request.user.artist == event.artist %}
        <script src="{% static 'music/js/delete_popup.js' %}" async></script>
        <script src="{% static 'music/js/delete_event.js' %}" async></script>
        <script src="{% static 'music/js/snippets/components/photo_upload.js' %}"></script>
        <script>
            $('.change-photo').uploadPhoto('{% url 'music:event_photo_upload' event.artist.id event.id %}');
        </script>
    {% else %}
        <script src="{% static 'music/js/like_unlike_event.js' %}" async></script>
        <script src="{% static 'music/js/sub_unsub_event.js' %}" async></script>
        <script src="{% static 'music/js/join_quit_event.js' %}" async></script>
    {% endif %}
<script>
    // set location on window object to user on api call
    window.absoluteAddress = '{{ event.location }}';
</script>
<script src="{% static 'secret/google_places.js' %}"></script>
<script src="{% static 'music/js/snippets/api/google_geocode_service.js' %}"></script>
<!-- load google geocode script async -->
<script>
(function() {
    var script = document.createElement('script');
    script.src = GOOGLE_GEOCODE_URL;
    script.type = "text/javascript";
    script.async = true;
    script.defer = true;
    document.body.insertBefore(script, document.body.children[0]);
})();
</script>
{% endif %}
{% endblock %}