Trooze-master/Trooze/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('music.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Trooze-master/home/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^', views.gotomusic, name='gotomusic'),
]

Trooze-master/music/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'music'

urlpatterns = [
    # albums view
    url(r'^', views.landing_page, name="landing_page"),

    # register user
    url(r'^register/$', views.UserRegisterView.as_view(), name="register"),

    # register artist
    url(r'^register-artist/$', views.UserRegisterArtistView.as_view(), name="register_artist"),

    # login user
    url(r'^login/$', views.UserLoginView.as_view(), name="login"),

    # logout user
    url(r'^logout/$', views.logout_user, name="logout"),

    url(r'^artists/', include([
        # search artists
        url(r'^search/form/$', views.search_artists_form, name="search_artists_form"),
        url(r'^search/$', views.search_artists, name="search_artists"),
    ])),

    url(r'^artist/(?P<artist_id>[0-9]+)/', include([
        # artist details
        url(r'^$', views.artist_details, name="artist_details"),
        # update artist details
        url(r'^update/$', views.ArtistUpdateView.as_view(), name="artist_update"),
        # follow artist
        url(r'^follow/$', views.follow_artist, name="follow_artist"),
        # unfollow artist
        url(r'^unfollow/$', views.unfollow_artist, name="unfollow_artist"),
        # like artist
        url(r'^like/$', views.like_artist, name="like_artist"),
        # unlike artist
        url(r'^unlike/$', views.unlike_artist, name="unlike_artist"),
        # upload photo
        url(r'^upload-photo/$', views.artist_photo_upload, name="artist_photo_upload"),
        # artist events
        url(r'^event/', include([
            # create event
            url(r'^create/$', views.ArtistCreateEventView.as_view(), name="create_event"),
            # specific event
            url(r'^(?P<event_id>[0-9]+)/', include([
                # event details
                url(r'^$', views.event_details, name="event_details"),
                # delete event
                url(r'^delete/$', views.delete_event, name="delete_event"),
                # update event
                url(r'^update/$', views.EventUpdateView.as_view(), name="update_event"),
                # like event
                url(r'^like/$', views.like_event, name="like_event"),
                # unlike event
                url(r'^unlike/$', views.unlike_event, name="unlike_event"),
                # subscribe event
                url(r'^subscribe/$', views.subscribe_event, name="subscribe_event"),
                # unsubscribe event
                url(r'^unsubscribe/$', views.unsubscribe_event, name="unsubscribe_event"),
                # join event
                url(r'^join/$', views.join_event, name="join_event"),
                # quit event
                url(r'^quit/$', views.quit_event, name="quit_event"),
                # upload photo
                url(r'^upload-photo/$', views.event_photo_upload, name="event_photo_upload"),
            ])),
        ])),
    ])),

    url(r'^album/', include([
        # search album
        url(r'^search/$', views.album_search, name="album_search"),
        # create album
        url(r'^create/$', views.AlbumCreateView.as_view(), name="album_create"),
    ])),

    url(r'^album/(?P<album_id>[0-9]+)/', include([
        # single album view
        url(r'^$', views.album_details, name="album_details"),
        # update album
        url(r'^update/$', views.AlbumUpdateView.as_view(), name="album_update"),
        # delete album
        url(r'^delete/$', views.delete_album, name="album_delete"),
        # like album
        url(r'^like/$', views.like_album, name="like_album"),
        # unlike album
        url(r'^unlike/$', views.unlike_album, name="unlike_album"),
        # copy album
        url(r'^copy/$', views.copy_album, name="copy_album"),
        # upload photo
        url(r'^upload-photo/$', views.album_photo_upload, name="album_photo_upload"),
    ])),

    url(r'^albums/', include([
        # albums view
        url(r'^$', views.AlbumsView.as_view(), name="albums"),
        # search for albums
        url(r'^search/form/$', views.search_albums_form, name="search_albums_form"),
        url(r'^search/$', views.search_albums, name="search_albums"),
        # all songs
        url(r'^songs/$', views.all_songs, name="all_songs"),
    ])),


    url(r'^album/(?P<album_id>[0-9]+)/song/', include([
        # create song
        url(r'^create/$', views.SongCreateView.as_view(), name="song_create"),
        # specific song
        url(r'^(?P<song_id>[0-9]+)/', include([
            # update song
            url(r'^update/$', views.SongUpdateView.as_view(), name="song_update"),
            # delete song
            url(r'^delete/$', views.delete_song, name="song_delete"),
            # favorite song
            url(r'^favorite/$', views.favorite_song, name="favorite_song"),
            # upload audio
            url(r'^upload-song/$', views.upload_song, name="upload_song"),
        ])),
    ])),
]

Trooze-master/website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^', include('home.urls')),
]

Trooze-master/music/views.py
from django.views.generic import (
    View,
    ListView,
)
from django.db.models import (
    Q,
    CharField,
    Value as V,
)
from django.db.models.functions import (
    Length,
    Concat,
)
from django.contrib.auth import (
    authenticate,
    login,
    logout
)
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.forms import modelform_factory
from django.core.paginator import (
    Paginator,
    PageNotAnInteger,
    EmptyPage
)
from django.conf import settings
from .models import (
    Album,
    Song,
    Artist,
    Event,
)
from .forms import (
    UserRegisterForm,
    ArtistForm,
    UserLoginForm,
    AlbumForm,
    SongForm,
    ArtistSongForm,
    EventForm,
)
from .const import (
    IMAGE_FILE_TYPES,
    AUDIO_FILE_TYPES,
)
from .utils import (
    bad_image_file_type,
    bad_audio_file_type,
    song_already_exists,
    album_already_exists,
    create_copied_album,
    create_copied_song
)

"""""""""""""""""""""
    Landing Page
"""""""""""""""""""""


def landing_page(request):
    if request.user.is_authenticated:
        if hasattr(request.user, 'artist'):
            return redirect('music:artist_details', artist_id=request.user.artist.id)
        return redirect('music:albums')
    return render(request, 'music/home/home.html')


"""""""""""""""""""""""
   User Registration
"""""""""""""""""""""""


class UserRegisterView(View):
    form_class = UserRegisterForm
    template_name = 'music/home/registration/register.html'

    def get(self, request):
        context = {'form': self.form_class(), 'not_logged_in': True}
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST or None)
        context = {'form': form, 'not_logged_in': True}
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('music:albums')
            return render(request, self.template_name, context)
        return render(request, self.template_name, context)


class UserRegisterArtistView(View):
    form_class = UserRegisterForm
    form_class2 = ArtistForm
    template_name = 'music/home/registration/register_artist.html'

    def get(self, request):
        context = {'form': self.form_class(), 'form2': self.form_class2(), 'not_logged_in': True}
        return render(request, self.template_name, context)

    def post(self, request):
        user_form = self.form_class(request.POST or None)
        artist_form = self.form_class2(request.POST or None, request.FILES or None)
        context = {'form': user_form, 'form2': artist_form, 'not_logged_in': True}
        if user_form.is_valid() and artist_form.is_valid():
            user = user_form.save(commit=False)
            user.artist = artist_form.save(commit=False)
            # check uploaded file type
            username = user_form.cleaned_data['username']
            password = user_form.cleaned_data['password1']
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('music:artist_details', artist_id=user.artist.id)
            return render(request, self.template_name, context)
        return render(request, self.template_name, context)


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'music/home/registration/login.html'

    def get(self, request):
        return render(request, self.template_name, {'form': self.form_class(), 'not_logged_in': True})

    def post(self, request):
        form = self.form_class()
        username = request.POST.get('username', None)
        password = request.POST.get('password', None)
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                if hasattr(user, 'artist'):
                    return redirect('music:artist_details', artist_id=user.artist.id)
                return redirect('music:albums')
            else:
                return render(request, 'error.html', {'message': 'This account has been disabled'})
        context = {'form': form, 'not_logged_in': True}
        return render(request, self.template_name, context)


def logout_user(request):
    logout(request)
    return redirect('music:login')


"""""""""""""""""
   Album Views
"""""""""""""""""


# albums view
class AlbumsView(LoginRequiredMixin, ListView):
    template_name = 'music/albums.html'
    context_object_name = 'albums'

    def get_queryset(self):
        return Album.get_albums_by_user(self.request.user)


# single album view
@login_required
def album_details(request, album_id):
    album = Album.cached_album_by_pk(album_id, related='user')
    songs = album.song_set.all()
    context = {'songs': songs, 'album': album}
    return render(request, 'music/album_details.html', context)


"""""""""""""""""
  Album Creation
"""""""""""""""""


class AlbumCreateView(LoginRequiredMixin, View):
    form_class = AlbumForm
    template_name = 'music/album_form.html'

    def get(self, request):
        form = self.form_class()
        # if artist, pre put name
        if hasattr(request.user, 'artist'):
            artist_name = request.user.artist.full_name
            form = self.form_class({'artist': artist_name})
        context = {'form': form, 'action': 'create'}
        return render(request, self.template_name, context)

    def post(self, request):
        form = self.form_class(request.POST or None, request.FILES or None)
        if form.is_valid():
            album = form.save(commit=False)
            album.user = request.user
            # check if album already exists
            if Album.get_albums_by_user(request.user).filter(name__exact=album.name).exists():
                return album_already_exists(request, form, album)
            if request.FILES:  # make sure FILES dictionary is not empty
                file_type = album.logo_file.url.split('.')[-1].lower()
                if file_type not in IMAGE_FILE_TYPES:
                    return bad_image_file_type(request, form, album)
            album.save()
            return redirect('music:albums')
        context = {'form': form, 'action': 'create'}
        return render(request, self.template_name, context)


"""""""""""""""""
  Album Update
"""""""""""""""""


class AlbumUpdateView(LoginRequiredMixin, View):
    form_class = modelform_factory(Album, form=AlbumForm, exclude=['logo_file'])
    template_name = 'music/album_form.html'

    def get(self, request, album_id):
        album = Album.cached_album_by_pk(album_id, related='user')
        if album.user != request.user:
            return render(request, 'error.html', {'message': 'You can not edit this album'})
        form = self.form_class(album.as_object())
        context = {'form': form, 'album': album, 'action': 'update'}
        return render(request, self.template_name, context)

    def post(self, request, album_id):
        album = Album.cached_album_by_pk(album_id, related='user')
        if album.user != request.user:
            message = 'You are trying to make an action you are not authorized to do'
            return render(request, 'error.html', {'message': message})
        form = self.form_class(request.POST or None, request.FILES or None)
        if form.is_valid():
            updated_album = form.save(commit=False)
            all_albums_except_current = Album.get_albums_by_user(request.user).exclude(pk=album_id)
            # check if album already exists
            if all_albums_except_current.filter(name__exact=updated_album.name).exists():
                return album_already_exists(request, form, album, action='update')
            album.update_fields(updated_album, exclude=['logo_file', 'user'])
            album.save()
            return redirect('music:album_details', album_id=album_id)
        context = {'form': form, 'album': album, 'action': 'update'}
        return render(request, self.template_name, context)


"""""""""""""""""
  Album Deletion
"""""""""""""""""


# album delete
@login_required
def delete_album(request, album_id):
    album = Album.cached_album_by_pk(album_id, related='user')
    if album.user == request.user:
        album.delete()
        return redirect('music:albums')
    message = 'You can not delete this album'
    return render(request, 'error.html', {'message': message})


"""""""""""""""""""""
  Album Photo Upload
"""""""""""""""""""""


@login_required
@csrf_exempt
def album_photo_upload(request, album_id):
    album = Album.cached_album_by_pk(album_id, related='user')
    if request.user != album.user:
        return render(request, 'error.html', {'message': 'You can not upload a picture for this album'})
    file = request.FILES.get('file')
    if file is None:
        return JsonResponse({'no_file': False})
    file_type = file.name.split('.')[-1].lower()
    if file_type not in IMAGE_FILE_TYPES:
        return JsonResponse({'not_image': True})
    album.file_to_delete = album.logo_file
    album.logo_file = file
    album.save()
    return JsonResponse({'uploaded': True})


"""""""""""""""""
  Album Search
"""""""""""""""""


@login_required
def album_search(request):
    query = request.GET.get('q', None)
    albums = []
    if query:
        albums = Album.get_albums_by_user(request.user)
        albums = albums.filter(
            Q(name__icontains=query) |

Trooze-master/music/templates/music/partials/album_image.html
{% load staticfiles %}

<a href="{% url 'music:album_details' album.id %}" class="album-image">
    {% if album.logo_file %}
        <img src="{{ album.logo_file.url }}" alt="{{ album.name }}" title="{{ album.name }}" class="img-fluid" />
    {% elif album.logo %}
        <img src="{{ album.logo }}" alt="{{ album.name }}" title="{{ album.name }}" class="img-fluid" />
    {% else %}
        <img src="{% static 'music/img/no_image.png' %}" alt="{{ album.name }}" title="{{ album.name }}" class="img-fluid" />
    {% endif %}
</a>

Trooze-master/music/templates/music/partials/album_image_upload.html
{% load staticfiles %}

<div class="image-wrapper">
    {% include 'music/partials/album_image.html' %}

    {% if request.user == album.user %}
        {% include 'music/partials/upload_new_photo.html' %}
    {% endif %}
</div>

Trooze-master/music/templates/music/partials/form_template.html
<div class="form-group">
    {% for field in form %}
        {% if field.is_hidden %}
            {{ field }}
        {% else %}
            <div class="form-group">
                {{ field.label_tag }}
                {% if field.field.required %}<span class="required-asterik">*</span>{% endif %}
                {{ field }}
            </div>
        {% endif %}
        {% if field.errors %}
            <p class="text-danger">{{ field.errors }}</p>
        {% endif %}
    {% endfor %}

    {% if form2 %}
        {% for field in form2 %}
            {% if field.is_hidden %}
                {{ field }}
            {% else %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {% if field.field.required %}<span class="required-asterik">*</span>{% endif %}
                    {{ field }}
                </div>
            {% endif %}
            {% if field.errors %}
                <p class="text-danger">{{ field.errors }}</p>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>
{% csrf_token %}

Trooze-master/music/templates/music/partials/head_snippet.html
{% load staticfiles %}
<base href="/">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy" />
<link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
<link rel="stylesheet" href="{% static 'music/css/base.css' %}" />

Trooze-master/music/templates/music/partials/navbar.html
<nav class="navbar navbar-inverse">

    <div class="container-fluid">

        <!-- navbar-header -->
        <div class="navbar-header">
            <a href="/" class="navbar-brand satisfy" href="{% url 'music:albums' %}">Trooze &nbsp;</a>
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-icons" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <!-- navbar-collapse -->
        <div class="collapse navbar-collapse" id="navbar-icons">
          <!-- navbar-icons -->
          <ul class="nav navbar-nav">
              {% if request.user.artist %}
                <li id="artist">
                    <a href="{% url 'music:artist_details' request.user.artist.id %}">
                        <span class="glyphicon glyphicon-user"></span> {{ request.user.artist.full_name }}
                    </a>
                </li>
              {% endif %}
              <li id="albums">
                  <a href="{% url 'music:albums' %}">
                      <span class="glyphicon glyphicon-cd"></span> Albums
                  </a>
              </li>
              <li id="songs">
                  <a href="{% url 'music:all_songs' %}">
                      <span class="glyphicon glyphicon-music"></span> Songs
                  </a>
              </li>
              {% if request.user.artist %}
                <li id="events">
                    <a href="{% url 'music:artist_details' request.user.artist.id %}">
                        <span class="glyphicon glyphicon-calendar"></span> Events
                    </a>
                </li>
              {% endif %}
          </ul>
          <!-- navbar-form -->
          {% if albums and albums.0.user == request.user and not artist %}
              <form action="{% url 'music:album_search' %}" method="get" class="navbar-form navbar-left">
                <div class="form-group search-album">
                  <input type="text" name="q" class="form-control input-sm" placeholder="Search Your Albums..." />
                </div>
                <div class="form-group search-album">
                    <button type="submit" class="btn btn-default btn-sm">Let's go!</button>
                </div>
              </form>
          {% endif %}
          <!-- navbar-right -->
          <ul class="nav navbar-nav navbar-right">
            <li style="top: 4px;">
                <a href="">
                    <span class="glyphicon glyphicon-bell"></span>
                </a>
            </li>
            <li>
                <a href="{% url 'music:album_create' %}">
                    <span class="glyphicon glyphicon-plus"></span> Album
                </a>
            </li>
            {% if request.user.artist %}
            <li>
                <a href="{% url 'music:create_event' request.user.artist.id %}">
                    <span class="glyphicon glyphicon-plus"></span> Event
                </a>
            </li>
            {% endif %}
            <li>
            {% if not_logged_in %}
                <a href="{% url 'music:login' %}">
                    <span class="glyphicon glyphicon-log-in"></span> Login
                </a>
            {% else %}
                <a href="{% url 'music:logout' %}">
                    <span class="glyphicon glyphicon-off"></span> Logout
                </a>
            {% endif %}
            </li>
          </ul>
        </div>
        <!-- /navbar-collapse -->
    </div>
</nav>

Trooze-master/music/templates/music/partials/single_album.html
<div class="thumbnail">
    {% if not albums %}
        {% include 'music/partials/album_image_upload.html' %}
    {% else %}
        {% include 'music/partials/album_image.html' %}
    {% endif %}
  <div class="caption">
    <h3>{{ album.name }}</h3>
    <p>{{ album.artist }} ({{ album.genre }})</p>
    {% with likes=album.likers.count %}
        <div class="like-badge-wrapper">
            <p class="label label-warning like-badge">{{ likes }} like{{ likes|pluralize }}</p>
        </div>
    {% endwith %}
    <p>
        <a href="{% url 'music:album_details' album.id %}" class="btn btn-primary btn-sm" role="button">View</a>
        {% if request.user != album.user %}
            {% if request.user in album.likers.all %}
                <a href="{% url 'music:unlike_album' album.id %}" class="btn btn-default btn-sm album-like-unlike" role="button">
                    <span class="glyphicon glyphicon-thumbs-down"></span> <span class="like-unlike">Unlike</span>
                </a>
            {% else %}
                <a href="{% url 'music:like_album' album.id %}" class="btn btn-default btn-sm album-like-unlike" role="button">
                    <span class="glyphicon glyphicon-thumbs-up"></span> <span class="like-unlike">Like</span>
                </a>
            {% endif %}
            <a href="{% url 'music:copy_album' album.id %}" data-name="{{ album.name }}" class="btn btn-default btn-md copy-album" role="button">
                <span class="glyphicon glyphicon-save"></span>
            </a>
        {% else %}
            <!-- update form -->
            <a href="{% url 'music:album_update' album.id %}" class="btn btn-default btn-sm" role="button">
                <span class="glyphicon glyphicon-edit"></span>
            </a>
            <!-- delete confirm -->
            <a href="{% url 'music:album_delete' album.id %}" data-name="{{ album.name }}" class="btn btn-default btn-sm delete-album" role="button">
                <span class="glyphicon glyphicon-trash"></span>
            </a>
        {% endif %}
    </p>
  </div>
</div>

Trooze-master/music/templates/music/partials/upload_new_photo.html
<div class="change-photo">
  <span class="change-photo-text">
      Upload New Photo
    <i class="fa fa-camera" aria-hidden="true"></i>
  </span>
</div>